/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "final.h"
#include <stdbool.h>
#include <stdio.h>


int TotalArray[1000];
int count = 0;
int numberRemoved = 0;
int arraySize = 0;


bool_t *
append_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	count ++;
	
	if(arraySize > 1000){
		result = false;
	}
	else{
		for(int i=0;i<10;i++){
			//TotalArray[10* (count-1)+i]=argp[i];
			TotalArray[arraySize+i]=argp[i];
		}  
		
		arraySize = arraySize + 10; //add 10 int successfully
		
		
		printf("current stored list: ");
		for (int i=0;i<arraySize;i++){
			printf("%d ", TotalArray[i]);
		}
		printf("\n");
		
		
		result = true;
	}


	return &result;
}

int *
query_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	int index = argp[0];
	if(index > arraySize-1){
		result = -1;
	}
	else{
		result = TotalArray[index];
	}
	return &result;
}

bool_t *
remove_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t result  ;

	/*
	 * insert server code here
	 */
	int index =  argp[0];
	if(index > arraySize -1){
		result = false;
	}else{
		
		//shift left to right
		for (int i=index;i<arraySize;i++){
			TotalArray[i]=TotalArray[i+1];
		}
		
		arraySize --;
		printf("list after last removed: ");
		//for (int i=0;i<10*count-numberRemoved;i++){
		for (int i=0;i<arraySize;i++){
			printf("%d ", TotalArray[i]);
		}
		printf("\n");
		
		
		result = true;
	}
	

	return &result;
}





















