/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "final.h"
#include <stdbool.h>
#include <stdio.h>


int newArr[10];
int queryPos;
int removePos;

void
hw2_1(char *host, char *oper)
{
	CLIENT *clnt;
	bool_t  *result_1;
	int *append_1_arg;
	int  *result_2;
	int  query_1_arg;
	bool_t  *result_3;
	int  remove_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, HW2, DATE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	if(strcmp(oper,"append")==0){

		append_1_arg = newArr;
		result_1 = append_1(append_1_arg, clnt);
		if (result_1 == (bool_t *) NULL) {
			clnt_perror (clnt, "call failed");
		}else{
			printf("append success!\n");
		}
		

	}else if(strcmp(oper,"query")==0){
		query_1_arg = queryPos;
		result_2 = query_1(&query_1_arg, clnt);
		if (result_2 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}else if(*result_2 == -1){
			printf("query position exceeds the scope of the ordered list!\n");
		}
		else{
			printf("query success! result is %d\n", *result_2);
		}
	
	
	}else if(strcmp(oper,"remove")==0){
		remove_1_arg = removePos;
		result_3 = remove_1(&remove_1_arg, clnt);
		if (result_3 == (bool_t *) NULL) {
			clnt_perror (clnt, "call failed");
		}else if(*result_3 == 1 ){
			//printf("%d\n", *result_3);
			printf("remove success!\n");
		
		}

		else{
			
			printf("remove position exceeds the scope of the ordered list!\n");
		}
	
	}

	

	
	
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char *oper;
	

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	
	host = argv[1];
	oper = argv[2];
	
	if(strcmp(oper,"append")==0){
		for (int i=0; i<10;i++){
    			if(argv[3+i]!=NULL){
    				newArr[i] = atoi(argv[3+i]);
    			}
    			else{
    				printf("please append 10 integer! (only first 10 integer are considered)\n");
    				exit (0);
    			}
    			
		}
	}else if(strcmp(oper,"query")==0){
		queryPos = atoi(argv[3]);
	
	}else if(strcmp(oper,"remove")==0){
		removePos = atoi(argv[3]);
	
	}
	
	hw2_1 (host, oper);
exit (0);
}
